name: Sync Fork

on:
  schedule:
    - cron: '0 5 * * 1'   # weekly, before the build workflow runs at 6am
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork with upstream
        env:
          GH_TOKEN: ${{ secrets.TOKEN }} # github token doesnt want to work :/
        run: |
          gh repo sync ItzPancakse/helium-browser-bin --source s6muel/helium-browser-bin
